### PR TITLE
Add job for mattermost-push-proxy

### PR DESCRIPTION
**Pull request by dlahn**

### CODE REVIEW

**Comment by hanzei** [comment]
@cpanato I've found this old PR. Could you please take a look? Is this something we still want?

**Comment by cpanato** [comment]
yes, i will look this PR
thanks @hanzei for followup and that @dlahn for the PR

**Comment by hanzei** [comment]
@cpanato Just want to remind you of this PR

**Comment by cpanato** [comment]
thanks for this contribution

I was thinking about this one, and it is possible to convert this job to use a JobDSL? will be much more easy to read and maintain.

**Comment by hanzei** [comment]
@dlahn What do you think about this?

**Comment by hanzei** [comment]
This PR has become orphaned and will be closed. Still, thanks for your contribution @dlahn

**Comment by hanzei** [comment]
@cpanato Would you please close this?

**Pull request closed without merging**
